version: "3"

services:
  api-deliveries-pg:
    image: bitnami/postgresql
    ports:
      - 172.20.170.67:5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apideliveries
